---
title: "Inversion_Sim_Params"
author: "Sara Michele Schaal"
date: "2/6/2020"
output: html_document
---
## Create list of parameters for model
```{r}
### Number of Parameters that vary
  num_param <- 15
  
## List of Parameters in model
  first.seed <- 3383282 #runif(1, 0, 10000000)
  mu_prop <- c(0.01, 0.1)#, 1e-04, 1e-03)
  mu_inv <- c(0, 1e-03, 1e-06)#1e-05, 1e-07) #orders of magnitude higher or lower than mu_base
  sigmaK <- c(0.75, 1.5, 3) # reduce to 3 values
  alpha <- c(0.002, 0.2) #sd of effect sizes of QTN mutations
    # 0.2 because 95% of observations will be <0.4, and a mutation of 0.5 in a homozygote will give 1.0 optimum
  reps <- c(1:5)
  N <- 1000 # some subset we will do 10,000 interesting cases
  envar <- c(0,0.1) # should we run this? if heritability was less does that impact do a subset! 
  
  ## note migration rates are set up to take on two different values need to edit 
  ## for loop and num_sim below if you want to alter migration rates between populations
  mig1 <- c(0.001, 0.01, 0.1, 0.25, 0.4, 0.5)
  mig2 <- c(0.001, 0.01, 0.1, 0.25, 0.4, 0.5)
  chrom_num <- 21
  recom <- 1e-6
  burnin <- 10000
  theta1 <- 1
  theta2 <- -1
  dom <- 2 # 2 is false and 1 is true in the code there is an issue with the letter F converting to FALSE
  
## Number of total simulations
  num_sims <- length(mu_prop)*length(mu_inv)*length(sigmaK)*length(alpha)*length(reps)*length(N)*length(envar)*length(mig1)*length(recom)*length(burnin)*length(theta1)*length(theta2)*length(chrom_num)
  
## colnames vector
  columns <- c("seed", "muProp", "muInv", "sigmaK", "alpha", "rep", "n", "enVar", "mig1", "mig2", "theta1", "theta2", "burnin", "chromNum", "r", "dom")

## Time per sim varies based on parameters
 # min <- (num_sims/72)*
  hours <- (num_sims/72)*3
  days <- hours/24
  
  params <- matrix(nrow = 0, ncol = num_param)
  for(b in 1:length(mu_prop)){
    for(i in 1:length(mu_inv)){
      for(k in 1:length(sigmaK)){
        for(a in 1:length(alpha)){
          for(r in 1:length(reps)){
            for(n in 1:length(N)){
              for(e in 1:length(envar)){
                for(m in 1:length(mig1)){
                  new.row <- c(mu_prop[b], mu_inv[i], sigmaK[k], alpha[a],
                              reps[r], N[n], envar[e], mig1[m], mig2[m], theta1, 
                              theta2, burnin, chrom_num, recom, dom)
                  params <- rbind(params, new.row)
                }
              }
            }
          }
        }
      }
    }
  }

seeds <- seq(first.seed, (first.seed+nrow(params)-1), by = 1)
df.params <- cbind(seeds, params)

colnames(df.params) <- columns
rownames(df.params) <- NULL
head(df.params)
tail(df.params)
dim(df.params)
df.params <- as.data.frame(df.params)

removeLowInvMu_df <- df.params[df.params$muInv != 0.000001,]
write.table(removeLowInvMu_df, "./results/Inversion/20220302_reviews/FullSet_dfparams.txt")
#write.table(df.params, "src/invSimParams.txt", row.names = FALSE)
#test.data #<- df.params[c(1,2155, sample(1:2000, 2)),]
#write.table(test.data, "src/test_invSimParams.txt", row.names = FALSE)
df.params <- as.data.frame(df.params)

df.params.rerun <- rbind(df.params[df.params$seed %in% seq(from = 3384362, to = 3384781, by = 2),], 
                     df.params[df.params$seed >= 3384780,])

df.params.rerun2 <- rbind(df.params[df.params$seed <= 3385439 & df.params$seed >= 3385143,])


df.params[df.params$mig1 == 0.4 & df.params$muBase ==  0.000001 
            & df.params$sigmaK == 0.75 & df.params$alpha == 0.002 
            & df.params$enVar == 0 & df.params$muInv == 0.001, ] 
df.params[df.params$seed == 3384842,]

removeLowInvMu_df[removeLowInvMu_df$mig1 == 0.1 & removeLowInvMu_df$muProp == 0.1 & 
                    removeLowInvMu_df$sigmaK == 1.5 & removeLowInvMu_df$alpha == 0.002 &
                    removeLowInvMu_df$enVar == 0.1 & removeLowInvMu_df$muInv == 0.001,]

# 20210930
#3384723 poly low mig (0.01) strong selec 



#3384602 poly low low mig weak select - no island 3384962
#3384603 poly low mig weak select - no island 3384963
#3384604 poly mod mig weak select - no island 3384964
#3384605 poly high mig weak select - no island 3384965 
#3384606 poly high high mig weak select - no island 3384966

#3384482 poly low low mig mod select - no island 3384842
#3384483 poly low mig mod select - island 3384843
#3384484 poly mod mig mod select - no island 3384844
#3384485 poly high mig mod select - no island 3384845
#3384486 poly high high mig mod select - no island 3384846

#3384362 poly low low mig strong select - no islands just high fst across all 3384722
#3384363 poly low mig strong select - no islands just high fsts 3384723
#3384364 poly mod mig strong select - islands 3384724
#3384365 poly high mig strong select - no islands 3384725
#3384366 poly high high mig strong select - no islands 3384726

removeLowInvMu_df[removeLowInvMu_df$mig1 == 0.4 & removeLowInvMu_df$muProp == 0.1 & 
                    removeLowInvMu_df$sigmaK == 0.75 & removeLowInvMu_df$alpha == 0.002 &
                    removeLowInvMu_df$enVar == 0.1 & removeLowInvMu_df$muInv == 0.00,]

#3383522 oligo low low mig weak select - inv 3383942
#3383523 oligo low mig weak select - inv 3383943
#3383524 oligo mod mig weak select - inv 3383944
#3383525 oligo high mig weak select - inv 3383945
#3383526 oligo high high mig weak select - inv 3383946

#3383462 oligo low low mig mod select - inv 3383822
#3383463 oligo low mig mod select - inv 3383823
#3383464 oligo mod mig mod select - inv 3383824
#3383465 oligo high mig mod select - inv 3383825
#3383466 oligo high high mig mod select - inv 3383826

#3383282 oligo low low mig strong select - inv 3383702
#3383283 oligo low mig strong select - inv 3383703
#3383284 oligo mod mig strong select - inv 3383704
#3383345 oligo high mig strong select - inv 3383705
#3383346 oligo high high mig strong select - inv 33836706

## Concept fig list
#orange square - inversions 3384962 no inversion control 3384602
#purple triangle - inversions 3384843 no inversion control 3384483
#yellow star - inversion 3384724 no inversion control 3384364 
#blue circle - inversion 3384725 no inversion control 3384365

df.params[df.params$mig1 == 0.25 & df.params$muBase ==  0.0000001 
            & df.params$sigmaK == 0.75 & df.params$alpha == 0.2 
            & df.params$enVar == 0 & df.params$muInv == 0.001, ]

# semi oligo 0.5 mig 3385447 (3385537) 
# semi oligo 0.25 mig 3385445 (3385535)


# mono low low mig weak select 
# mono low mig weak select - 
# mono mod mig weak select - no island
# mono high mig weak select - no island
# mono high high mig weak select - no island

# mono low low mig mod select - no island
# mono low mig mod select - island
# 3385654 mono mod mig mod select - no island (3385744)
# mono high mig mod select - no island
# mono high high mig mod select - no island

# mono low low mig strong select - no islands just high fst across all
# mono low mig strong select - no islands just high fsts
# mono mod mig strong select - islands (3385714)
# 3385625 mono high mig strong select - no islands (3385715)
# 3385626 mono high high mig strong select - no islands (3385716)
#3385627 (3385717)
#cp 3385445_outputMutations.txt ../noInvControls/
#cp 3385445noSel_outputMutations.txt ../noInvControls/
```

## additional parameters
```{r}

### Number of Parameters that vary
  num_param <- 15
  
## List of Parameters in model
  first.seed.2 <- 3385442 #runif(1, 0, 10000000)
  mu_base <- c(1e-08, 1e-09) #, 1e-04, 1e-03)
  mu_inv <- c(0, 1e-03)#1e-05, 1e-07) #orders of magnitude higher or lower than mu_base
  sigmaK <- c(0.75, 1.5, 3) # reduce to 3 values
  alpha <- 0.2 #sd of effect sizes of QTN mutations
    # 0.2 because 95% of observations will be <0.4, and a mutation of 0.5 in a homozygote will give 1.0 optimum
  reps <- c(1:5)
  N <- 1000 # some subset we will do 10,000 interesting cases
  envar <- 0 # should we run this? if heritability was less does that impact do a subset! 
  
  ## note migration rates are set up to take on two different values need to edit 
  ## for loop and num_sim below if you want to alter migration rates between populations
  mig1 <- c(0.001, 0.01, 0.1, 0.25, 0.4, 0.5)
  mig2 <- c(0.001, 0.01, 0.1, 0.25, 0.4, 0.5)
  chrom_num <- 21
  recom <- 1e-6
  burnin <- 10000
  theta1 <- 1
  theta2 <- -1
  dom <- 2 # 2 is false and 1 is true in the code there is an issue with the letter F converting to FALSE
  
## Number of total simulations
  num_sims <- length(mu_base)*length(mu_inv)*length(sigmaK)*length(alpha)*length(reps)*length(N)*length(envar)*length(mig1)*length(recom)*length(burnin)*length(theta1)*length(theta2)*length(chrom_num)
  
## colnames vector
  columns <- c("seed", "muBase", "muInv", "sigmaK", "alpha", "rep", "n", "enVar", "mig1", "mig2", "theta1", "theta2", "burnin", "chromNum", "r", "dom")

##

params <- matrix(nrow = 0, ncol = num_param)
  for(b in 1:length(mu_base)){
    for(i in 1:length(mu_inv)){
      for(k in 1:length(sigmaK)){
        for(a in 1:length(alpha)){
          for(r in 1:length(reps)){
            for(n in 1:length(N)){
              for(e in 1:length(envar)){
                for(m in 1:length(mig1)){
                  new.row <- c(mu_base[b], mu_inv[i], sigmaK[k], alpha[a],
                              reps[r], N[n], envar[e], mig1[m], mig2[m], theta1, 
                              theta2, burnin, chrom_num, recom, dom)
                  params <- rbind(params, new.row)
                }
              }
            }
          }
        }
      }
    }
  }

seeds <- seq(first.seed.2, (first.seed.2+nrow(params)-1), by = 1)
df.params.2 <- as.data.frame(cbind(seeds, params))
str(df.params.2 )
colnames(df.params.2) <- columns
rownames(df.params.2) <- NULL
head(df.params.2)
tail(df.params.2)
dim(df.params.2)
write.table(df.params.2, "src/invSimParams_2.txt", row.names = FALSE)

rerun1 <- c(3385626, 3385639, 3385670, 3385688, 3385703, 3385720)
df.params.3<- df.params.2[df.params.2$seed %in% rerun1,]

```


## Visualization of Parameter's effects
```{r}

 plot(dnorm(x=seq(-5,5,0.01), mean = 0, sd=1))
 x<- seq(-2,2,0.001)
 plot(x,dnorm(x, mean = 0, sd=0.07))
 plot(x,dnorm(x, mean = 0, sd=0.7))
 plot(x,dnorm(x, mean = 0, sd=0.1), xlim=c(-1,1))
 plot(x,dnorm(x, mean = 1, sd=0.2), xlim=c(-2,2), col = "cornflowerblue")
 points(x,dnorm(x,mean = -1, sd = 0.2), col = "limegreen")
 
df.summary[df.summary$seed == 3383871, ]
```

### Test Parameters
```{r}
## List of Parameters in model
  first.seed <- 3383282 
  mu_base <- c(1e-07, 1e-06)
  mu_inv <- c(0, 1e-03) 
  sigmaK <- 0.9 
  alpha <- c(0.002, 0.2) #sd of effect sizes of QTN mutations
    # 0.2 because 95% of observations will be <0.4, and a mutation of 0.5 in a homozygote will give 1.0 optimum
  reps <- c(1:2)
  N <- 1000 
  envar <- 0
  
  ## note migration rates are set up to take on two different values need to edit 
  ## for loop and num_sim below if you want to alter migration rates between populations
  mig1 <- c(0.001, 0.01, 0.1, 0.5)
  mig2 <- c(0.001, 0.01, 0.1, 0.5)
  chrom_num <- 21
  recom <- 1e-6
  burnin <- 10000
  theta1 <- 1
  theta2 <- -1
  dom <- 2

  num_Testsims <- length(mu_base)*length(mu_inv)*length(sigmaK)*length(alpha)*length(reps)*length(N)*length(envar)*length(mig1)*length(recom)*length(burnin)*length(theta1)*length(theta2)*length(chrom_num)
  
  params <- matrix(nrow = 0, ncol = num_param)
  for(b in 1:length(mu_base)){
    for(i in 1:length(mu_inv)){
      for(k in 1:length(sigmaK)){
        for(a in 1:length(alpha)){
          for(r in 1:length(reps)){
           # for(n in 1:length(N)){
             # for(e in 1:length(envar)){
                for(m in 1:length(mig1)){
                  new.row <- c(mu_base[b], mu_inv[i], sigmaK[k], alpha[a],
                              reps[r], N, envar, mig1[m], mig2[m], theta1, 
                              theta2, burnin, chrom_num, recom, dom)
                  params <- rbind(params, new.row)
                }
            #  }
           # }
          }
        }
      }
    }
  }
  
params
seeds <- seq(first.seed, (first.seed+nrow(params)-1), by = 1)
df.params <- cbind(seeds, params)
colnames(df.params) <- columns
rownames(df.params) <- NULL
testTestParams <- head(df.params)
df.paramsPreLim <- df.params
write.table(testTestParams, "testTestParams.txt", row.names = FALSE)
write.table(df.params, "testParams.txt", row.names = FALSE)

```




```{r}
N = 1000
prop = 0.1 #proportion of genome where QtNs can arise
(genome_size = 1e5*20)
  
#mutations per generation
mu_base*prop*2*N*genome_size

# Can we approximate m_c based on the range of effect sizes we expect to arise?
alpha_sd/2
alpha_sd*4

alpha_levels <- c()

print((alpha_sd[1]/2)) #small effect size
cbind(alpha=alpha_sd[1]/2, 
      sigma_k, 
      m_c = m_crit(alpha_sd[1]/2, theta.1, theta.2, sigma_k, N))

cbind(alpha=alpha_sd[1]*4, 
      sigma_k, 
      m_c = m_crit(alpha_sd[1]*4, theta.1, theta.2, sigma_k, N))

cbind(alpha=alpha_sd[2]/2, 
      sigma_k, 
      m_c = m_crit(alpha_sd[2]/2, theta.1, theta.2, sigma_k, N))

cbind(alpha=alpha_sd[2]*4, 
      sigma_k, 
      m_c = m_crit(alpha_sd[2]*4, theta.1, theta.2, sigma_k, N))
```
